### ISSUE TITLE
Responsive / Slide Animation Intial Size Issue

### ISSUE THREAD

**Issue by maxxcrawford** [jcobb/basic-jquery-slider#124]
#### Found an issue with the slides being out of position whenever you have:
- Responsive set to _True_
- Animtype set to _Slide_
- The site is initalliy loaded in a smaller view, forcing your slide container to have a smaller set width than what is initially set in the _$(document).ready_ call.

![Screen Shot 2013-03-21 at 4 37 15 PM](https://f.cloud.github.com/assets/2692333/288285/c68d7c6c-926f-11e2-8c1c-b71ac858511c.jpg)

**What is needed is to have the resize function fire whenever the container width is smaller than the defined width param.**

Thanks!

**Comment by deavy** [comment]
Have another issue: you need to use `state.slidecount` instead of `settings.slidecount`.
